travis:
  secure:
    BINSTAR_TOKEN: JlhX7MWURFKSEUoeSbUzgviCmuAUIau66AvMhW+tRrQQGARZ1VpBbs2iqELLO/TPK+ZtRmncJwC9CM31IWMekfXn7iR6r7a4d30f9bPkvM8PYzkgSoJeUlfKPcKPK3rYJ8zxe02q1X0UX4iD1Sjjth8SUe8GO7XOqV9XdUqQD5lDo7ogWCdhXi+W1/QLhuLGZPa6R3mEZU+0yOLWSFq1RVAPWQvf0PcgyfjErmkC8VVk+XN8LebR9Nuc5PQFYAarhxgu8qtESmNkCPBUkw3Mi/PUvYg6UOCTqoiMmacQEqa7Ci4jzQdjPfFg4xkZoEAv8c+SfKXP08Bcxi1RH2ZdITJaB2VUeRECs0B/uBpfg6terLRhy6GJqEdhBg8GGjpCxUEQ5d8kTH6YVoK0Tl6o5Dvjh7SX3bK04N/OmQQZ6WczPbnvhGXLXVOao8qiwNqzk9hiIiOI4BeNqU29OOP3xo7I1mb4LN5tcSa29LKt2so+NijoXHmp0yOetvWNMB+Fm/ESbTDdQ1vDRlZDo2dveix/fhURkN0gmC4plejDc00iIe+Bh802BRe/lRCzAowgwg6b1CoT84Gzg4WCY0ZplMqDUDrLvPbQlzJLqrsJispqd6h6NvCsoVAZIQ4yOvCBmr/yZhHykkKgNXnUc/A2BMuEkqMtSICj3hgp/wBvbWE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
